hash-format = "sha256"

[[files]]
file = "config/gravestones.json"
hash = "91ae5d3e610e9053671027bd08be221c7cdf9fe947b5c7e26ffb48b1d2d9b330"

[[files]]
file = "config/treeharvester.json5"
hash = "c1c62127f08d8c3155024f0ced0f2484e17be267472d0ca93b9640ae00a5db49"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "e82351fda29ccc40665eb47b13cf325db77d6ccbd3a57c2208c54ae4e5c6f45f"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "90c625d1398c6a19531d9d35b74a456cbbd7da3a19ec4da98ec13a3ba22c855e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b2103de7f3d13a7b7868890afd358e51f93bea4914e226fc0fbe53bdb84ff7e8"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3c6b206bface93aee9075a0c18c0ebe91026932610c52ae86489f1055342bbbf"
metafile = true

[[files]]
file = "mods/elytra-trinket-updated.pw.toml"
hash = "71b7125d8685f0515d708c3da698b44d1ec6bc02ea7f664409b9cf0346613501"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fa8be992c1e3efbd030ef6a84409b766a936deb3fc3d06b657f8e468745044f0"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "639b8c8c8d82b4b640b0f92619ac8e864579af729dd9a1c27534c8b2aef14bf2"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4eb0060a2288f8f0f97e87eec65493e3e21f1f81ce6a6343e54ed296aadee957"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5787b1deb7975af608901df0bf16b1e5de2452c98808f6a205c35aaa83e9f56a"
metafile = true

[[files]]
file = "mods/otterlib.pw.toml"
hash = "f9ed647ab1f647a278a815b94feaa8fc5404334023bc8bc6bb381dc4980a994a"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "0c29d19475a2eb997b70e5418f1ba9c63c04b441e1bd96a955c3dbbfbd6fa867"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "cecc601e14ecf7740a08402459d37b234a6560878d3a03b161e85aaaabc3f0d8"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "29a47d3c5c467e8c4cfde49f927238867839f7518c8444a0e1c5b8c6657600e9"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "a93862dc31f56fae1ba90acda3d4b6b6afbab76720ade5b21f6026316d2f5625"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
hash = "898ed168073d22ebec4574565edf34d5d38c87e7ae9d43c6ed56bdac5be5d005"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0e0970dafc9680fba4dc73434baad6aa7dee91ab4994f33b2493ea5b4c59931d"
metafile = true

[[files]]
file = "mods/sit!.pw.toml"
hash = "5fd1bcbbbbb955a1e0c170db7675e18bebfdf0dbe89f05507f7ca653aead7843"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "c545f2d9b2cca20ead494fa706f32e6c0d610f1692b1d3269d574a838ab4e577"
metafile = true

[[files]]
file = "mods/trinkets-canary.pw.toml"
hash = "b9e1215808705e3a86f12e703ecbc1a814b40f8134d44cb765d3dfe335d959b2"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "73bd3e12b7f552db549143950fdd4df8c8429d9c1f65be9e21d9d1128f10e81b"
metafile = true
