name = "vanilla"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15b4f2b3de0511b33b41272c77f2e77ceceb9ce8acf2d9f05d4f84f4721a3041"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
