hash-format = "sha256"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "e82351fda29ccc40665eb47b13cf325db77d6ccbd3a57c2208c54ae4e5c6f45f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "fa8be992c1e3efbd030ef6a84409b766a936deb3fc3d06b657f8e468745044f0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4eb0060a2288f8f0f97e87eec65493e3e21f1f81ce6a6343e54ed296aadee957"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5787b1deb7975af608901df0bf16b1e5de2452c98808f6a205c35aaa83e9f56a"
metafile = true

[[files]]
file = "mods/santas-delight.pw.toml"
hash = "dba2c8968daa05de4ee5eb575d5ecf8c0b27439521edb3de439470cc40cd2cf0"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "a93862dc31f56fae1ba90acda3d4b6b6afbab76720ade5b21f6026316d2f5625"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0e0970dafc9680fba4dc73434baad6aa7dee91ab4994f33b2493ea5b4c59931d"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "73bd3e12b7f552db549143950fdd4df8c8429d9c1f65be9e21d9d1128f10e81b"
metafile = true
