name = "vanilla"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd7d402311c66c29efe7b483befac43c39f3fd5e0a8d8a17fd267b39c438449f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
