name = "vanilla"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de82449fdeaf057f13ecd6d2fad393fd8796d31c3d9073d1f08f3313efbf60c7"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
