hash-format = "sha256"

[[files]]
file = "config/resource_backpacks/client/appearance.json"
hash = "be055dc1eaefc6ba33bcfeafdad28bfd88d75d2f1625d9cb89365c0cf5ffa27d"

[[files]]
file = "config/resource_backpacks/common/backpacks.json"
hash = "bcea691bd8b44e0f642b11c891bd50d844a776604678c1031d587a802daee4a0"

[[files]]
file = "config/resource_backpacks/common/chest_loot.json"
hash = "8e5981442a0df5917127e0d9b6d30c6f30e542be0017671d2cf4d9de5100e2d5"

[[files]]
file = "config/resource_backpacks/common/entity_config.json"
hash = "b0909893a6fcdb4a8549770ff8f8b11bf7f4bd474f353a01a8df3a384c9222f8"

[[files]]
file = "config/treeharvester.json5"
hash = "062fb148cb2639d5412171423aecc00e8bb7baa218862788b65425f3704a621e"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "8a9a2ca29d73feeaccc6ab6e9a3a9c2bb7da23fd322597ebcfb05610862281ba"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1c977f2f3a1f335f3716ee67d19cfc62e491182a74456596e1348106c48cb2ab"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7018c36808d8314c4f33a03ce8a018dd58eef00365d8506a5154d79052144386"
metafile = true

[[files]]
file = "mods/blooming-biosphere.pw.toml"
hash = "41dae7504acd7b7af1ba002189fc5cf8d22364736b587c7cfb2899011bff04d0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "33ea0878eae19825e9cc034bfbde5435addfe790e9ad551b0f51db970d9ccc71"
metafile = true

[[files]]
file = "mods/call-your-horse.pw.toml"
hash = "d4172fc1c3dfdfb373297dd74d321a54f20d5eea5829d00a49170f739c06cd9c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "2ffba149ee8a8c283ec050c1ad5b5e5ef930854443f5b52fc3ef233d877a6253"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "af6fbeb17ff88d8c35b7fd1dab31855babe9b843df173c9e4850556462a94c01"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "b0f409eca358de3ecae8aac8a64ef88c458d00b7b85411aece5d6db8c70747e3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "0d5c7ff4961a493b99c17379f477d68e8e52fd8e975460afabdab2e4261a8cc4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "8ac0b6ec229c65ae0670a447f4e5c628f7245a5f51cc512bbeb3780ed300b4c5"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "daacfd077d443f89b8babfc2db310be8ac04a2dcd06f9c1d98e727595bec6de0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f1da925ae791df99a453d1e135cb3c7a390c861a6ae9db299e19ffc83dfed680"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "52e8593d35c1b8c6847f64e9066a75ffa80a2598323703fbfaade5a7da577780"
metafile = true

[[files]]
file = "mods/indypets.pw.toml"
hash = "953716c094f01c9e88f6e4af0959fd82cedd8930d6021b3db825685cb0f15c56"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "03d499df9fda53f31a42192738de2f2c2243d009c471f62a8c33ae1a988716c6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2902fadd11f70190c60ff3ccbb11960518f2e44cc8d29e02d0e6e9b9cabc2fe4"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f5e83da1cf19d3bbb2340bc8fe713975efde3ca3d141c7731888e6e26b6ac8e3"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "47a051efb9b7bc9b14335a84e0412621d888939ca32a583eae660bad044984cb"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "647767b5fd7a2aa5e11ca7a4d0e53451d95275d84404a3f1ac228124f88a0cd0"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "c4e4f777917d7a9d5a9af58ac6d7f58e770683a8cb2e8763555b8812f36cd90d"
metafile = true

[[files]]
file = "mods/otterlib.pw.toml"
hash = "17219c582eb01bdd49c158423ee3e65c2b2c4d3b3d04517a7308554e24d149ee"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "0dec359d02dd53ee2048e4e721a66096710853939efa3bb463e6ef53884a4271"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "b614a5d3b3220bd7c601c9c1f63e436dc63903853857b08a314406b93ea18062"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "01289f0d842e7718acef2bf246fc14b03a059f1cf95d9041190c8479c4519cab"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "7031c11b9f5b4ff7b432d599b2cc317093562f12bba6a1e740a9d77e0143bddb"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "1509362b8d6154efebb9e50b110faa0cf2e523449ad65ed2f3508538b9ae9ef9"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "41fffd8c008c2e0c9940172559a50c1e28c11bcc06fcd41b3423a555843b0881"
metafile = true

[[files]]
file = "mods/resource-backpacks.pw.toml"
hash = "ca064b00b7aa6007c535dc956db4c491857d64ffe6c070056de4b312a74f13db"
metafile = true

[[files]]
file = "mods/resource-config-api.pw.toml"
hash = "b03332e17b7b990d034745da4cdf5eac25b4c2c2eaf5e06a472b5aa672ac1c71"
metafile = true

[[files]]
file = "mods/resource-library.pw.toml"
hash = "a1508c5d3abaae4e6567ddbaef6e8eefb5c8523424ace9d60b604997125874a4"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "5478fa27be82c6e92191a5b95142383ab8e1798c23990998c1a94b710d7f8435"
metafile = true

[[files]]
file = "mods/sit!.pw.toml"
hash = "c2cb45a8a691d592f96ad87c65bf8df379fe4398d2e5831e9c6a6a66fa81bd98"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ef5b990499a2223875dd6151d6a254ed2d5fed98d8f2e4038a2f0b5a8a9e2b54"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "aff8d365e1f9ca7641542ad2ea10f5f633e579061251e2594894f86da9e29c3e"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "82cc41c439575118a33c9bbbd35c136762d81a167d097a0adf62db94dbd43238"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "9bad046f07a54611fa1d08f255d7db95364d8d6193f044b223f5ae987aa3fa33"
metafile = true

[[files]]
file = "mods/vanilla-backpacks.pw.toml"
hash = "51b998c9648a97f9ff4eee9c5fa64695b0130bc03ce16a3ad7ee99023d458622"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "968e705f6b42ca65c25bf43c726d08cb1d51df234386775b15d734bac6d6444e"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "93c87ce5757ef74481afbd13893fd423ae7e718fd73303f864c7fa76c72f1165"
metafile = true
