name = "Prox Farmers"
author = "mel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e52ebf200a72c2a872ab2fae959eab2501df889848c5fe49bbfb739e0f10cab7"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"

[options]
acceptable-game-versions = []
datapack-folder = "./datapacks"
